apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: klab
  sources:
    - chart: gitea
      repoURL: https://dl.gitea.com/charts/
      targetRevision: 9.6.1
      helm:
        values: |
          ingress:
            enabled: true
            className: traefik
            hosts:
              - host: git.klab.home
                paths:
                  - path: /
                    pathType: Prefix
          persistence:
            enabled: true
            claimName: gitea-pvc
          gitea:
            APP_NAME: "Gitea: Klab"
            admin:
              username: klab
              password: superpassword
              email: "klab@klab.home"
              passwordMode: keepUpdated
            config:
              database:
                DB_TYPE: postgres
                HOST: postgres.klab.home:5432
                NAME: gitea
                USER: gitea
                PASSWD: superpassword
                SCHEMA: public
              cache:
                enable: false
          redis:
            enabled: false
          redis-cluster:
            enabled: false
          postgresql-ha:
            enabled: false
          postgresql:
            enabled: false



  destination:
    server: https://kubernetes.default.svc
    namespace: gitea