apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: klab
  sources:
    - chart: portainer
      repoURL: https://portainer.github.io/k8s/
      targetRevision: v1.8.0 # Replace with the Longhorn version you'd like to install or upgrade to
      helm:
        parameters:
          - name: "nodeSelector"
            value: "worker"
          - name: "service.type"
            value: "ClusterIP"
          - name: "ingress.enabled"
            value: "true"
          - name: "ingress.annotations"
            value: "kubernetes.io/ingress.class: traefik"
          - name: "ingress.hosts.host"
            value: "portainer.klab.home"
          - name: "persistence.enabled"
            value: "true"
          - name: "persistence.existingClaim"
            value: "portainer-pvc"
          - name: "persistence.storageClass"
            value: "longhorn"

  destination:
    server: https://kubernetes.default.svc
    namespace: portainer