#upstream api_server {
#     server api:3000;
#}

server {
 listen 80;
 server_name frontend;
 location / {
   # This would be the directory where your React app's static files are stored at
   root /etc/nginx/templates;
   try_files $uri /index.html;
 }

#location /services/m {
#   proxy_set_header X-Real-IP $remote_addr;
#   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#   proxy_set_header X-NginX-Proxy true;
#   proxy_pass http://backend:8080/services/m;
#   proxy_ssl_session_reuse off;
#   proxy_set_header Host $http_host;
#   proxy_cache_bypass $http_upgrade;
#   proxy_redirect off;
# }
}


server {
    listen 80;
    server_name longhorn.klab.home;

    location / {
        proxy_pass http://10.0.2.10/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
    }
}


server {
    listen 80;
    server_name portainer.klab.home;

    location / {
        proxy_pass http://10.0.2.10/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
    }
}

upstream registry {
    server registry.klab.home:5000;
}

server {
    listen 80;
    server_name registry.klab.home;

    location / {
        # Do not allow connections from docker 1.5 and earlier
        # docker pre-1.6.0 did not properly set the user agent on ping, catch "Go *" user agents
        if ($http_user_agent ~ "^(docker\/1\.(3|4|5(?!\.[0-9]-dev))|Go ).*$" ) {
          return 404;
        }
        proxy_pass              http://127.0.0.1:5000/;
        proxy_set_header        X-Real-IP $remote_addr;# pass on real client's IP
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-NginX-Proxy true;
        proxy_set_header        Host $http_host; # required for docker client's sake
        proxy_cache_bypass      $http_upgrade;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_read_timeout      900;
    }
    location /v2/ {
        proxy_pass http://registry;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}