services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    container_name: registry
    volumes:
      - /opt/services/registry/data:/var/lib/registry
      - /opt/services/registry/registry.conf:/etc/registry/default.conf
    environment:
      #      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_ADDR: '0.0.0.0:5000'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '[http://registry.klab.home]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'


  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    restart: always
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=KLab Registry
      - REGISTRY_URL=http://registry.klab.home:5000
      - SINGLE_REGISTRY=true
      - DELETE_IMAGES=true
    depends_on:
      - registry