apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: klab-environment
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/dev/apps/tmp
    repoURL: https://github.com/KLab-env/environment.git
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: klab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=false